FROM debian:trixie

LABEL MAINTAINER=cl2037829916@gmail.com



RUN apt-get update && apt-get install wget -y

RUN mkdir npc

RUN wget https://github.com/ehang-io/nps/releases/download/v0.26.10/linux_amd64_client.tar.gz -c && tar -zvxf ./linux_amd64_client.tar.gz -C npc

WORKDIR /npc
