version: "3"
services:
  gitlab:
    environment:
    - DEBUG=true
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - GITLAB_HOST=www.imclius.top
    - GITLAB_PORT=12080
    - GITLAB_SECRETS_DB_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_OTP_KEY_BASE=qcs-gitlab-app
    - GITLAB_SECRETS_SECRET_KEY_BASE=qcs-gitlab-app
    - GITLAB_SSH_PORT=12022
    - SMTP_USER=cl2037829916@gmail.com
    - SMTP_PASS=
    - IMAP_USER=cl2037829916@gmail.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=USER+%{key}@gmail.com
    - IMAP_PASS=
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    image: sameersbn/gitlab:16.8.1
    depends_on:
    - redis
    - postgresql
    ports:
    - "12080:80"
    - "12022:22"
    restart: always
    volumes:
    - /Container/gitlab/logs:/var/log/gitlab
    - /Container/gitlab/config:/etc/gitlab
    - /Container/gitlab/data:/var/opt/gitlab
  postgresql:
    environment:
    - DB_EXTENSION=pg_trgm,btree_gist
    - DB_NAME=gitlabhq_production
    - DB_PASS=password
    - DB_USER=gitlab
    image: sameersbn/postgresql:14-20230628
    restart: always
  redis:
    command:
    - --loglevel warning
    image: redis:6.2.6
    restart: always
  version: "3"
services:
  pgadmin4:
    image: elestio/pgadmin@sha256:4f96197989c6a7bbca4df4101c3fb406e9a1ae752f081107bbc2ebacd27bce5b
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=cl2037829916@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=
    - PGADMIN_LISTEN_PORT=56082
    ports:
    - "56082:56082"
    volumes:
    - /Container/pgAdmin/servers.json:/pgadmin4/servers.json
