version: '3'
services:
  zerotier:
    image: zyclonite/zerotier:1.12.2
    container_name: zerotier-one
    entrypoint: /usr/sbin/zerotier-cli join 565799d8f605857e
    devices:
      - /dev/net/tun
    network_mode: host
    restart: always
    volumes:
      - '/var/lib/zerotier-one:/var/lib/zerotier-one'
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
